Scene Changes:
  - UnityProject/Assets/**/*.unity

SquareStation:
  - UnityProject/Assets/Scenes/MainStations/SquareStation.unity
  
PogStation:
  - UnityProject/Assets/Scenes/MainStations/PogStation.unity

FallStation:
  - UnityProject/Assets/Scenes/MainStations/FallStation.unity

OutpostStation:
  - UnityProject/Assets/Scenes/MainStations/OutpostStation.unity

BoxStation:
  - UnityProject/Assets/Scenes/MainStations/BoxStationV1.unity

Documentation:
  - docs/**/*

Sprite Work:
  - UnityProject/Assets/Textures/**/*.png
  - UnityProject/Assets/Textures/**/*.PNG
  - AssetLibrary/**/*.png
  - AssetLibrary/**/*.PNG

UI:
  - UnityProject/Assets/Scripts/UI/**/*
  - UnityProject/Assets/Scenes/UI/**/*
  
  

